### ISSUE TITLE
Does this still work

### ISSUE THREAD

**Issue by mrjamesperry** [samuelleach/uk-atlas#4]
Hi,
Newbie here, but this looks like it could be very useful.  I'm looking for something that pulls the boundary files from http://geoportal.statistics.gov.uk/
Then exports as topojson files and alters projection wgs 1984
These files can then be improted to PowerBi shapemapper

Would this tool do this?  Is there a simple guide?

**Comment by samuelleach** [comment]
Hello @mrjamesperry - it's quite possible that parts or all of the Makefile are broken. I have not run this Makefile (which was inspired by this repository https://github.com/topojson/world-atlas) in about three years. See if you can read through the Makefile which shows which files you need to download as well as the dependencies and command line commands you need to run.
